# $FreeBSD$

PORTNAME=	voluptuous-serialize
DISTVERSION=	2.4.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	y@trombik.org
COMMENT=	Convert Voluptuous schemas to dictionaries

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
